-- Garante encoding no cliente
SET client_encoding = 'UTF8';

INSERT INTO neighborhoods (name) VALUES
(U&'Am\00e9rica'),
('Bolaxa'),
('Carreiros'),
('Cassino'),
('Castelo Branco'),
('Centro'),
(U&'Cidade de \00c1gueda'),
('Cidade Nova'),
('COHAB I'),
('COHAB II'),
('COHAB IV'),
('Distrito Domingos Petroline'),
('Frederico Ernesto Buchholz'),
(U&'Get\00falio Vargas'),
(U&'Hidr\00e1ulica'),
('Lagoa'),
(U&'Lar Ga\00facho'),
('Miguel de Castro Moreira'),
('Nossa Senhora dos Navegantes'),
('Parque Marinha'),
('Parque Residencial Coelho'),
('Parque Residencial Jardim do Sol'),
('Parque Residencial Salgado Filho'),
(U&'Parque Residencial S\00e3o Pedro'),
('Povo Novo'),
('Profilurbi'),
('Quinta'),
(U&'Santa Rita de C\00e1ssia'),
(U&'S\00e3o Paulo'),
('Senandes'),
('Vila Bernardeth'),
(U&'Vila Jun\00e7\00e3o'),
('Vila Maria'),
('Vila Maria Jos\00e9'),
('Vila Militar'),
(U&'Vila Nossa Senhora de F\00e1tima'),
('Vila Rural'),
('Vila Santa Rosa'),
('Vila Santa Tereza'),
(U&'Vila S\00e3o Jo\00e3o'),
(U&'Vila S\00e3o Jorge'),
(U&'Vila S\00e3o Miguel'),
('Zona Portu\u00e1ria')
ON CONFLICT (name) DO NOTHING;
